# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3179c16
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: ema.luzakova@epfl.ch
author_name: Ema Luzakova, Ipek Begum Incesu, Ariane Fienga Schultheis
github_org: emaluzak
package_name: lynen_spiral
project_name: Lynen_Spiral
short_description: beta-oxidation of fatty acids
